### ISSUE TITLE
Is there a way to turn this of per image?

### ISSUE THREAD

**Issue by DanielTate** [wedevelopnl/silverstripe-webp-images#11]
For example I want most of my images to be .webp however some I would like to do something like:

`$Image.NotWebP.AbsoluteURL`

Is this possible or can I disable images in a config somewhere?

**Comment by NightJar** [comment]
Try `$Image.DisableWebP`
or `$Image.DisableWebP.AbsoluteURL` if you only wanted the URL string.

https://github.com/wedevelopnl/silverstripe-webp-images/blob/bb6546f833e71fb4b30db748bede27d0ece5caf7/src/Asset/ImageExtension.php#L17

**Comment by erikfrerejean** [comment]
@DanielTate per @NightJar you can disable the webp generation on a specific image using the `DisableWebP` method, however please note that when using that method in a template it sometimes behaves unexpected. See the "know issue" in the corresponding PR https://github.com/wedevelopnl/silverstripe-webp-images/pull/10#issuecomment-1451941710

**Comment by jenniferaslan** [comment]
Is there a way to do this for the Image on a DataObject class? I don’t seem to be able to get the suggested solution to work in my template and the DataObject is used in multiple templates anyway. I would like the logo images I'm uploading to a DataObject to not be processed as webp. Like, is there some way I can use `WebpGenerator::singleton()->setEnabled(false);` with my upload field: `$fields->addFieldToTab('Root.Main', UploadField::create('Logo', 'Logo')->setFolderName('Logos'));` or somewhere else in the DataObject class?
