### ISSUE TITLE
Upgrade for Silverstripe 5 and PHP 8.1

### ISSUE THREAD

**Issue by ghost** [wedevelopnl/silverstripe-webp-images#8]
Can you update the package for Silverstripe 5 and PHP 8.1?

**Comment by erikfrerejean** [comment]
@bitwingsde sorry for the late response, the package is already compatible with PHP 8.1 but we've updated the requirement.

As for a silverstripe 5 compatible update, I have added it to our backlog but at the moment we aren't developing for silverstripe 5 yet I do not yet know when this update will land on our roadmap.

**Comment by ghost** [comment]
Are there any upgrade plans yet? Silverstripe 5 has already been released.

**Comment by ricoschenker** [comment]
Any news? We use the module for several projects and would be very interested in the upgrade. Thanks!

**Comment by DanielTate** [comment]
Is this still being maintained?

**Comment by erikfrerejean** [comment]
Yes, we're still maintaining this module however haven't had time yet to update it. There is a SS5 upgrade PR now: https://github.com/wedevelopnl/silverstripe-webp-images/pull/12
